trigger:
- master

pool:
  vmImage: ubuntu-latest
  
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job
  - job: SecondJob
    steps:
    - bash: echo Build Second Job  
- stage: Dev Deploy
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo Dev Deploy
- stage: QA Deploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QA Deploy
- stage: Prod Deploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo Prod Deploy

  
